project_name: warp

release:
  github:
    owner: warpdl
    name: warp-releases
  replace_existing_draft: true
  header: |
    Welcome to this new release!

gomod:
  env:
    - CGO_ENABLED=1
    - GOPROXY=direct
    - GOPRIVATE=github.com/warpdl/warplib

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - binary: warpdl
    env:
      - CGO_ENABLED=0
      - GOPRIVATE=github.com/warpdl/warplib
      - GOPROXY=direct
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: "386"
      - goos: freebsd
        goarch: "386"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

archives:
  - rlcp: true
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

signs:
  - artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  - name: warpdl
    tap:
      owner: warpdl
      name: homebrew-tap
    commit_author:
      name: "Divkix"
      email: divkix@divkix.me
    folder: Formula
    homepage: "https://warpdl.org"
    description: "The official Warp CLI download manager"
    install: |-
      bin.install "warpdl"
    test: |
      system "#{bin}/warpdl --version"

scoops:
  - name: warpdl
    bucket:
      owner: warpdl
      name: scoop-bucket
    commit_author:
      name: "Divkix"
      email: divkix@divkix.me
    homepage: "https://warpdl.org"
    description: "The official Warp CLI download manager"

nfpms:
  - file_name_template: >-
      {{ .PackageName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    homepage: "https://warpdl.org"
    maintainer: Divanshu Chauhan <divkix@divkix.me>
    description: "The official Warp CLI download manager"
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - apk

dockers:
  - goarch: amd64
    dockerfile: goreleaser.Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=warp-cli"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goarch: arm64
    dockerfile: goreleaser.Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=warp-cli"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/warpdl/warp-cli:{{ .Version }}"
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-amd64"
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-arm64v8"
  - name_template: "ghcr.io/warpdl/warp-cli:latest"
    image_templates:
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-amd64"
      - "ghcr.io/warpdl/warp-cli:{{ .Tag }}-arm64v8"
