name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/warpdl/warplib
      GH_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - run: |
          git config --global user.name "divkix"
          git config --global user.email "social@anodite.co"
          git config --global user.password ${{ secrets.GH_PAT }}
          #git config --global credential.helper store
          #git credential-store --file ~/.git-credentials store
          echo "https://github.com/divkix:${secrets.GH_PAT}" >> ~/.git-credentials
          go get github.com/warpdl/warplib
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
