name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: divkix/reusable-workflows/.github/workflows/goreleaser-ci.yml@main
    with:
      use-upx: true
      upx-files: |
        dist/warp_linux_arm64/warp
        dist/warp_linux_amd64_v1/warp
        dist/warp_windows_amd64_v1/warp.exe
        dist/warp_darwin_amd64_v1/warp
        dist/warp_darwin_arm64/warp
