name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    env:
      GOPRIVATE: github.com/warpdl/warplib
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOPROXY: direct
    name: Goreleaser CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Configure git for private modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global url."https://divkix:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Tar files
        run: tar -cvf artifacts.tar dist/
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.tar
