name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: divkix/reusable-workflows/.github/workflows/goreleaser-ci.yml@main
    with:
      use-upx: false
