name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/warpdl/warplib
      GH_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GH_PAT }}"
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - run: |
          git config --global --add url."git@github.com:".insteadOf "https://github.com/"
          go get github.com/warpdl/warplib
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --snapshot --skip-publish --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
