name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true

jobs:
  goreleaser:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/warpdl/warplib
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
        # only run this step when the tag is not already created
      - if: startsWith(github.ref, 'refs/tags/') != 'true' && github.event.inputs.tag != ''
        name: Create and Push Tag
        run: |-
          git config --global user.email "divkix@divkix.me"
          git config --global user.name "Divanshu Chauhan"
          tag=${{ github.event.inputs.tag }} # if triggered by workflow_dispatch
          if [ -z "$tag" ]; then
            tag=${GITHUB_REF#refs/tags/}
          fi
          git tag -f -a -m "$tag" "$tag"
          git push -f origin "$tag"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-install-script:
    name: Update scripts/install.sh in warp-releases
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - name: Get latest tag from GitHub API
        run: |-
          # set latest_tag variable to latest tag of warpdl/warp-releases
          latest_tag=$(curl -s https://api.github.com/repos/warpdl/warp-releases/releases/latest | jq -r '.tag_name')
          # set it into GITHUB_ENV so it can be used in next steps
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Checkout warp-releases
        uses: actions/checkout@v3
        with:
          repository: warpdl/warp-releases
      - name: Replace version
        run: |
          sed -i "s/LATEST_RELEASE=.*/LATEST_RELEASE=\"${{ env.latest_tag }}\"/g" scripts/install.sh
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
