name: RTEST

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true

jobs:
  update-install-script:
    name: Update scripts/install.sh in warp-releases
    runs-on: ubuntu-latest
    env:
      CLI_REPO: warpdl/warp
    steps:
      - name: Get latest tag
        run: |-
          tag=${{ github.event.inputs.tag }} # if triggered by workflow_dispatch
          if [ -z "$tag" ]; then
            tag=${GITHUB_REF#refs/tags/}
          fi
          echo "RELEASE_VERSION=$tag" >> $GITHUB_ENV
      - name: Checkout warp
        uses: actions/checkout@v3
        with:
          path: ./warp
      - name: Copy existing files from warp to warpdl
        run: |-
          sed -i "s/version:.*/version: '${{ env.RELEASE_VERSION }}'/g" ./warp/snap/snapcraft.yaml
      - name: Commit changes
        run: |-
          git config --global user.email "divkix@divkix.me"
          git config --global user.name "Divkix"
          cd warp && git add . && git commit -m "bump to ${{ env.RELEASE_VERSION }}"
      - name: Push warp cli changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          repository: ${{ env.CLI_REPO }}
          directory: ./warp

  goreleaser:
    name: Run test
    needs: update-install-script
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Set up git
        run: git config --global url."https://divkix:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout
        uses: actions/checkout@v3
      - name: test
        run: |-
          git pull origin dev
          ls
          cd snap && cat snapcraft.yaml
